language: rust
rust:
- nightly-2019-08-27
before_script:
  - rustup component add rustfmt
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
