language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true
before_script:
  - rustup component add rustfmt
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
