[workspace]

members = [
    "spectrum",
]

[profile.dev]
opt-level = 1  # reasonable mix of compile/run speed

[profile.release]
lto = "thin"
debug = false  # turn on for profiling; bigger binaries but not any slower
codegen-units = 1  # makes it take a very long time
